# Data Preprocessing for Application Data
- table application_train.csv
---

## 0. Data and libraires

In [1]:
import pandas as pd
import numpy as np

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / 'src'

if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from eda_module import (
    plot_quantitative_distribution, plot_categorical_distribution, plot_binary_distribution, 
    plot_binary_vs_binary, plot_categorical_distribution, plot_quantitative_vs_binary,
    plot_categorical_vs_binary
)
from preprocess_module import create_imputed_quantitative_features, filter_high_nans_cols, drop_obs_with_nans_in_low_nan_cols

In [2]:
app_df = pd.read_csv(r"..\data\raw\application_train.csv")
print(f"Shape of app_df: {app_df.shape}")
app_df.head(10)

Shape of app_df: (307511, 122)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.0,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

## 1. Dropping technical or unnecessary columns

## 2. Filtering out variables with high number of NANs

In [3]:
df1, dropped_cols, summary_df = filter_high_nans_cols(
    df=app_df, 
    max_nans_share=0.45, 
    return_dropped_cols=True, 
    return_summary=True
)

In [4]:
print(f"Applicataion df: ")
print(f"before filtering out nans:  {app_df.shape}")
print(f"after filtering out nans: {df1.shape}")

Applicataion df:
before filtering out nans:  (307511, 122)
after filtering out nans: (307511, 73)

In [5]:
dropped_cols

['OWN_CAR_AGE',
 'EXT_SOURCE_1',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE']

In [6]:
summary_df[summary_df['keep']==False]

                         feature  nan_share  max_nans_share   keep
0                 COMMONAREA_AVG   0.698723            0.45  False
1                COMMONAREA_MEDI   0.698723            0.45  False
2                COMMONAREA_MODE   0.698723            0.45  False
3        NONLIVINGAPARTMENTS_AVG   0.694330            0.45  False
4       NONLIVINGAPARTMENTS_MEDI   0.694330            0.45  False
5       NONLIVINGAPARTMENTS_MODE   0.694330            0.45  False
6             FONDKAPREMONT_MODE   0.683862            0.45  False
7           LIVINGAPARTMENTS_AVG   0.683550            0.45  False
8          LIVINGAPARTMENTS_MEDI   0.683550            0.45  False
9          LIVINGAPARTMENTS_MODE   0.683550            0.45  False
10                 FLOORSMIN_AVG   0.678486            0.45  False
11                FLOORSMIN_MEDI   0.678486            0.45  False
12                FLOORSMIN_MODE   0.678486            0.45  False
13               YEARS_BUILD_AVG   0.664978            0.45  False
14              YEARS_BUILD_MEDI   0.664978            0.45  False
15              YEARS_BUILD_MODE   0.664978            0.45  False
16                   OWN_CAR_AGE   0.659908            0.45  False
17                  LANDAREA_AVG   0.593767            0.45  False
18                 LANDAREA_MEDI   0.593767            0.45  False
19                 LANDAREA_MODE   0.593767            0.45  False
20              BASEMENTAREA_AVG   0.585160            0.45  False
21             BASEMENTAREA_MEDI   0.585160            0.45  False
22             BASEMENTAREA_MODE   0.585160            0.45  False
23                  EXT_SOURCE_1   0.563811            0.45  False
24             NONLIVINGAREA_AVG   0.551792            0.45  False
25            NONLIVINGAREA_MEDI   0.551792            0.45  False
26            NONLIVINGAREA_MODE   0.551792            0.45  False
27                 ELEVATORS_AVG   0.532960            0.45  False
28                ELEVATORS_MEDI   0.532960            0.45  False
29                ELEVATORS_MODE   0.532960            0.45  False
30            WALLSMATERIAL_MODE   0.508408            0.45  False
31                APARTMENTS_AVG   0.507497            0.45  False
32               APARTMENTS_MEDI   0.507497            0.45  False
33               APARTMENTS_MODE   0.507497            0.45  False
34                 ENTRANCES_AVG   0.503488            0.45  False
35                ENTRANCES_MEDI   0.503488            0.45  False
36                ENTRANCES_MODE   0.503488            0.45  False
37                LIVINGAREA_AVG   0.501933            0.45  False
38               LIVINGAREA_MEDI   0.501933            0.45  False
39               LIVINGAREA_MODE   0.501933            0.45  False
40                HOUSETYPE_MODE   0.501761            0.45  False
41                 FLOORSMAX_AVG   0.497608            0.45  False
42                FLOORSMAX_MEDI   0.497608            0.45  False
43                FLOORSMAX_MODE   0.497608            0.45  False
44   YEARS_BEGINEXPLUATATION_AVG   0.487810            0.45  False
45  YEARS_BEGINEXPLUATATION_MEDI   0.487810            0.45  False
46  YEARS_BEGINEXPLUATATION_MODE   0.487810            0.45  False
47                TOTALAREA_MODE   0.482685            0.45  False
48           EMERGENCYSTATE_MODE   0.473983            0.45  False

## 3. Filtering out observation with small number of NANs in columns.

In [7]:
df2, filtering_cols_summary, remaining_nan_cols_summary, row_summary = drop_obs_with_nans_in_low_nan_cols(
    df = df1,
    max_nan_share = 0.05,
    return_filtering_cols_summary = True,
    return_remaining_nan_cols_summary = True,
    return_row_summary = True
)
df2.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
print(f"Applicataion df: ")
print(f"before filtering out obs with nans:  {df1.shape}")
print(f"after filtering out obs with nans: {df2.shape}")

Applicataion df:
before filtering out obs with nans:  (307511, 73)
after filtering out obs with nans: (304531, 73)

In [9]:
row_summary

n_rows_before         307511.000000
n_rows_after          304531.000000
n_rows_dropped          2980.000000
rows_dropped_share         0.009691
dtype: float64

In [10]:
filtering_cols_summary

DAYS_LAST_PHONE_CHANGE      0.000003
CNT_FAM_MEMBERS             0.000007
AMT_ANNUITY                 0.000039
AMT_GOODS_PRICE             0.000904
EXT_SOURCE_2                0.002146
DEF_30_CNT_SOCIAL_CIRCLE    0.003320
OBS_60_CNT_SOCIAL_CIRCLE    0.003320
OBS_30_CNT_SOCIAL_CIRCLE    0.003320
DEF_60_CNT_SOCIAL_CIRCLE    0.003320
NAME_TYPE_SUITE             0.004201
dtype: float64

In [11]:
remaining_nan_cols_summary

AMT_REQ_CREDIT_BUREAU_DAY     0.134988
AMT_REQ_CREDIT_BUREAU_HOUR    0.134988
AMT_REQ_CREDIT_BUREAU_MON     0.134988
AMT_REQ_CREDIT_BUREAU_WEEK    0.134988
AMT_REQ_CREDIT_BUREAU_QRT     0.134988
AMT_REQ_CREDIT_BUREAU_YEAR    0.134988
EXT_SOURCE_3                  0.197848
OCCUPATION_TYPE               0.313384
dtype: float64