# Application Train-Valid Split
- table - application_train.csv
---

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pathlib import Path
import sys

In [19]:
app_df = pd.read_csv(r"..\data\raw\application_train.csv")
print(f"Shape of app_df: {app_df.shape}")
app_df.head(10)

Shape of app_df: (307511, 122)

   SK_ID_CURR  TARGET  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR
0      100002       1  ...                       0.0                        1.0
1      100003       0  ...                       0.0                        0.0
2      100004       0  ...                       0.0                        0.0
3      100006       0  ...                       NaN                        NaN
4      100007       0  ...                       0.0                        0.0
5      100008       0  ...                       1.0                        1.0
6      100009       0  ...                       1.0                        2.0
7      100010       0  ...                       0.0                        0.0
8      100011       0  ...                       0.0                        1.0
9      100012       0  ...                       NaN                        NaN

[10 rows x 122 columns]

In [20]:
X, y = app_df.drop(columns=['TARGET']), app_df['TARGET']
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")

X_train: (215257, 121)
X_valid: (92254, 121)
y_train: (215257,)
y_valid: (92254,)

In [21]:
X_train.head()

        SK_ID_CURR  ... AMT_REQ_CREDIT_BUREAU_YEAR
159703      285133  ...                        0.0
79269       191894  ...                        6.0
232615      369428  ...                        NaN
33420       138717  ...                        2.0
88191       202381  ...                        0.0

[5 rows x 121 columns]

Since `sklearn.model_selection.train_test_split()` perserves `Pandas` indicies we can safely join them.

In [22]:
assert X_train.index.equals(y_train.index)
assert X_valid.index.equals(y_valid.index)

app_train_df = X_train.join(y_train)
app_valid_df = X_valid.join(y_valid)

In [23]:
PROJECT_PATH = Path.cwd().parent
DATA_SAVE_PATH = PROJECT_PATH / 'data' / 'interim'

if str(DATA_SAVE_PATH) not in sys.path:
    sys.path.insert(0, str(DATA_SAVE_PATH))

DATA_SAVE_PATH.mkdir(parents=True, exist_ok=True)

In [24]:
app_train_df.to_csv(DATA_SAVE_PATH / 'app_train.csv', index=False)
print(f"app_train_df saved to: DATA_SAVE_PATH\\'app_train.csv'")

app_valid_df.to_csv(DATA_SAVE_PATH / 'app_vaild.csv', index=False)
print(f"app_valid_df saved to: DATA_SAVE_PATH\\'app_vaild.csv'")

app_train_df saved to: DATA_SAVE_PATH\'app_train.csv'
app_valid_df saved to: DATA_SAVE_PATH\'app_vaild.csv'